# Generated by Django 4.1.2 on 2022-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('realisateur', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('datedecreation', models.DateField()),
            ],
        ),
    ]
